### ISSUE TITLE
chore: environment setup

### ISSUE THREAD

**Issue by EuFMD** [FAOEuFMD/milestones-dashboard#1]
- We need to create a blank canvas to deploy our frontend

- [x] Update README file
- [x] Set up React app with React Router Dom
- [x] Set up Express server
- [x] Set up CI/CD flow using deployment tool of choice

**Comment by EuFMD** [comment]
Staging environment set up on Render at the link here: 

https://milestones-dashboard-staging.onrender.com

**Comment by sssoja** [comment]
Staging environment set up on Render.

https://eufmd-tom-staging.onrender.com
