### ISSUE TITLE
refactor: remove select dashboard dropdown from navbar

### ISSUE THREAD

**Issue by sssoja** [FAOEuFMD/milestones-dashboard#33]
Remove
- the select dashboard dropdown
- remove the icons on the right
- the search bar if we intend not to use it

![Image](https://github.com/user-attachments/assets/88af01fc-4832-4143-8309-2defe5179e68)

**Comment by ACU017** [comment]
I removed the select and the icons from the nav bar I left the search bar commented just in case we want to use it in the future
