### ISSUE TITLE
styling: finalise homepage design

### ISSUE THREAD

**Issue by irenezatti** [FAOEuFMD/milestones-dashboard#42]
Changing app style color scheme based on FAO color palettes

**Comment by ACU017** [comment]
![image](https://github.com/user-attachments/assets/75fe98fc-fe5b-40a7-9a2e-0dcee261a80d)

Moodboard in Miro about the FAO page

**Comment by ACU017** [comment]
![Fao Green ](https://github.com/user-attachments/assets/4007cebe-b502-42c2-abae-29db099ba4e2)
![Palette Fao 2 - Brown and Grey ](https://github.com/user-attachments/assets/44920fc0-537c-423e-9c9a-b7c948beae7a)
[palette2-grey-browon.txt](https://github.com/user-attachments/files/16824500/palette2-grey-browon.txt)
![palette-green](https://github.com/user-attachments/assets/d5f90200-e8e1-468e-8dc4-0d6a31e81a25)
[palette-green.txt](https://github.com/user-attachments/files/16824501/palette-green.txt)

Palettes done with Coolors with Hexadecimal Colors for clarity @reedninety you can maybe add it into the documentation of the Frontend
