### ISSUE TITLE
reduce white space on homepage

### ISSUE THREAD

**Issue by sssoja** [FAOEuFMD/milestones-dashboard#80]
We have a lot of white space on the homepage above the key area pie chart - can we reduce this to improve the responsiveness?

Make sure to make the page responsive for desktop and smaller screen sizes. 

![Image](https://github.com/user-attachments/assets/5eb214b9-1c3f-4a5c-91f8-8e2f5b6010a4)

**Comment by PilarRius** [comment]
done
